server:
  port: 8080
spring:
  application:
    name: test_back
  datasource:
    url: jdbc:mysql://localhost:3306/test_board?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    password: root
    username: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: 192.168.0.12:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: user
      auto-offset-reset: earliest