server:
  port: 8080
spring:
  application:
    name: test_back
  datasource:
#    url: jdbc:h2:mem:test
#    username: sa
#    password:
    url: jdbc:mysql://localhost:3306/test_board?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    password: 0000
    username: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true